training:
  model_name: "protein_go_xlstm"
  task_type: "classification"
  batch_size: 32
  lr: 2e-5
  lr_warmup_steps: 1000
  lr_decay_until_steps: 10000
  lr_decay_factor: 0.1
  weight_decay: 0.01
  amp_precision: bfloat16
  weight_precision: float32
  enable_mixed_precision: true
  num_epochs: 10
  output_dir: "output/protein_go_xlstm"
  save_every_step: 500
  log_every_step: 50
  wandb_project: "protein_go_xlstm"
  torch_compile: false

model:
  type: "xLSTMLMModel"
  num_blocks: 8
  embedding_dim: 512
  mlstm_block:
    mlstm:
      num_heads: 8
  slstm_block:
    slstm:
      num_heads: 8
  slstm_at: [2, 5]
  context_length: 1024


dataset:
  # Path to your processed CSV file inside the 'data' directory
  path: "data/uniprot/data.csv"
  sequence_column: "Sequence"
  label_column: "Gene ontology IDs"

  
tokenizer:
  type: "file"
  path: "configs/protein_vocab.txt"
  pad_token: "[PAD]"
  unk_token: "[UNK]"

